### ISSUE TITLE
Installation fails on download checksum

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/dodoc_ynh#16]
Getting an error on installation: 

`YunoHost was able to download the asset 'main' (https://github.com/l-atelier-des-chercheurs/dodoc/archive/refs/heads/next-node.zip) for dodoc, but the asset doesn't match the expected checksum.
`
See full log: 
https://paste.yunohost.org/raw/wuhubukemi

**Comment by ericgaspar** [comment]
upstream versions are not published with version tags, we may encounter this issue from time to time. Should be fixed by now.
